<template>
  <div class="page-container">
    <el-tabs v-model="tab" @tab-change="load">
      <el-tab-pane label="奖品管理" name="rewards">
        <div class="toolbar"><el-button type="primary" @click="openReward()">新增奖品</el-button></div>
        <el-table :data="rewards" v-loading="loading" empty-text="暂无奖品，请点击右上角新增奖品">
          <el-table-column label="图片" width="86"><template #default="{row}"><el-image v-if="row.image" class="reward-thumb" :src="row.image" fit="cover" :preview-src-list="[row.image]" preview-teleported/><span v-else>-</span></template></el-table-column>
          <el-table-column prop="name" label="奖品" min-width="160"/><el-table-column prop="pointsCost" label="所需积分" width="110"/><el-table-column prop="stock" label="库存" width="90"/><el-table-column prop="perUserLimit" label="每人上限" width="100"/>
          <el-table-column label="需地址" width="90"><template #default="{row}">{{row.requiresAddress?'是':'否'}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status===1?'success':'info'">{{row.status===1?'上架':'下架'}}</el-tag></template></el-table-column>
          <el-table-column label="操作" width="160"><template #default="{row}"><el-button link type="primary" @click="openReward(row)">编辑</el-button><el-button v-if="row.status===1" link type="danger" @click="down(row)">下架</el-button></template></el-table-column>
        </el-table>
      </el-tab-pane>
      <el-tab-pane label="兑换订单" name="orders">
        <div class="toolbar"><el-select v-model="status" clearable placeholder="全部状态" @change="loadOrders"><el-option v-for="(v,k) in labels" :key="k" :label="v" :value="k"/></el-select></div>
        <el-table :data="orders" v-loading="loading">
          <el-table-column prop="redemptionNo" label="兑换单号" width="190"/><el-table-column prop="rewardName" label="奖品" min-width="130"/><el-table-column prop="quantity" label="数量" width="70"/><el-table-column prop="pointsCost" label="积分" width="90"/>
          <el-table-column label="收货信息" min-width="250"><template #default="{row}"><span v-if="row.addressSnapshot">{{address(row.addressSnapshot)}}</span><span v-else>无需收货地址</span></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag>{{labels[row.status]||row.status}}</el-tag></template></el-table-column><el-table-column label="快递" min-width="160"><template #default="{row}">{{row.courierCompany||'-'}} {{row.trackingNo||''}}</template></el-table-column>
          <el-table-column label="操作" width="150"><template #default="{row}"><el-button v-if="row.status==='pending_shipment'" link type="primary" @click="openShip(row)">发货</el-button><el-button v-if="row.status==='shipped'" link type="success" @click="finish(row)">完成</el-button></template></el-table-column>
        </el-table><el-pagination v-model:current-page="page" :total="total" :page-size="20" layout="prev,pager,next,total" @current-change="loadOrders"/>
      </el-tab-pane>
    </el-tabs>
    <el-dialog v-model="rewardVisible" :title="form.id?'编辑奖品':'新增奖品'" width="560px"><el-form label-width="90px">
      <el-form-item label="奖品名称" required><el-input v-model="form.name" maxlength="120"/></el-form-item><el-form-item label="说明"><el-input v-model="form.description" type="textarea"/></el-form-item>
      <el-form-item label="奖品图片"><el-upload class="reward-uploader" :show-file-list="false" :before-upload="beforeImageUpload" :http-request="uploadRewardImage"><div v-loading="uploading"><el-image v-if="form.image" class="reward-preview" :src="form.image" fit="cover"/><el-button v-else type="primary" plain>选择图片</el-button></div></el-upload><el-button v-if="form.image" class="remove-image" link type="danger" @click="form.image=''">移除图片</el-button><div class="upload-tip">支持 JPG、PNG、GIF、WebP，最大 2MB</div></el-form-item>
      <el-form-item label="所需积分"><el-input-number v-model="form.pointsCost" :min="1"/></el-form-item><el-form-item label="库存"><el-input-number v-model="form.stock" :min="0"/></el-form-item><el-form-item label="每人上限"><el-input-number v-model="form.perUserLimit" :min="0"/><span class="hint">0 表示不限</span></el-form-item><el-form-item label="收货地址"><el-switch v-model="form.requiresAddress"/></el-form-item><el-form-item label="状态"><el-switch v-model="form.active" active-text="上架"/></el-form-item>
    </el-form><template #footer><el-button @click="rewardVisible=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="uploading" @click="save">保存</el-button></template></el-dialog>
    <el-dialog v-model="shipVisible" title="兑换订单发货" width="460px"><el-form label-width="90px"><el-form-item label="快递公司"><el-input v-model="shipForm.courierCompany"/></el-form-item><el-form-item label="快递单号"><el-input v-model="shipForm.trackingNo"/></el-form-item></el-form><template #footer><el-button @click="shipVisible=false">取消</el-button><el-button type="primary" @click="ship">确认发货</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import{getPointsRewards,createPointsReward,updatePointsReward,disablePointsReward,getPointsRedemptions,shipPointsRedemption,completePointsRedemption,uploadImage}from'@/api'
const tab=ref('rewards'),loading=ref(false),rewards=ref<any[]>([]),orders=ref<any[]>([]),status=ref(''),page=ref(1),total=ref(0),rewardVisible=ref(false),shipVisible=ref(false),saving=ref(false),uploading=ref(false);const labels:any={pending_shipment:'待发货',shipped:'已发货',completed:'已完成',cancelled:'已取消'},form=reactive<any>({}),shipForm=reactive<any>({})
const reset=()=>Object.assign(form,{id:null,name:'',description:'',image:'',pointsCost:100,stock:0,perUserLimit:0,requiresAddress:true,active:true});const loadRewards=async()=>{loading.value=true;try{rewards.value=await getPointsRewards()as any}catch{rewards.value=[]}finally{loading.value=false}};const loadOrders=async()=>{loading.value=true;try{const r:any=await getPointsRedemptions({status:status.value||undefined,page:page.value,pageSize:20});orders.value=r?.list??r?.data?.list??[];total.value=r?.pagination?.total??r?.total??0}catch{orders.value=[]}finally{loading.value=false}};const load=()=>tab.value==='rewards'?loadRewards():loadOrders();const openReward=(r?:any)=>{reset();if(r)Object.assign(form,r,{active:r.status===1});rewardVisible.value=true}
const beforeImageUpload=(f:File)=>{if(!['image/jpeg','image/png','image/gif','image/webp'].includes(f.type)){ElMessage.error('只支持 JPG、PNG、GIF、WebP 格式');return false}if(f.size>2*1024*1024){ElMessage.error('图片大小不能超过 2MB');return false}return true};const uploadRewardImage=async(o:any)=>{uploading.value=true;try{const r:any=await uploadImage(o.file),url=r?.data?.url??r?.url;if(!url)throw Error();form.image=url;o.onSuccess?.(r);ElMessage.success('图片上传成功')}catch(e){o.onError?.(e);ElMessage.error('奖品图片上传失败，请重试')}finally{uploading.value=false}}
const save=async()=>{if(saving.value||uploading.value)return;if(!String(form.name||'').trim()){ElMessage.warning('请填写奖品名称');return}if(Number(form.pointsCost)<1){ElMessage.warning('所需积分必须大于 0');return}if(Number(form.stock)<0){ElMessage.warning('库存不能小于 0');return}saving.value=true;try{const d={...form,name:String(form.name).trim(),status:form.active?1:0};form.id?await updatePointsReward(form.id,d):await createPointsReward(d);ElMessage.success('已保存');rewardVisible.value=false;await loadRewards()}finally{saving.value=false}};const down=async(r:any)=>{await ElMessageBox.confirm('确定下架该奖品？');await disablePointsReward(r.id);await loadRewards()};const openShip=(r:any)=>{Object.assign(shipForm,{id:r.id,courierCompany:'',trackingNo:''});shipVisible.value=true};const ship=async()=>{if(!shipForm.courierCompany?.trim()||!shipForm.trackingNo?.trim()){ElMessage.warning('请填写快递公司和快递单号');return}await shipPointsRedemption(shipForm.id,shipForm);ElMessage.success('已发货');shipVisible.value=false;await loadOrders()};const finish=async(r:any)=>{await ElMessageBox.confirm('确认该兑换订单已完成？');await completePointsRedemption(r.id);await loadOrders()};const address=(a:any)=>`${a.contact} ${a.phone} ${a.province||''}${a.city||''}${a.district||''}${a.detail||''}`;onMounted(loadRewards)
</script>
<style scoped>.page-container{background:#fff;padding:20px;border-radius:8px}.toolbar{display:flex;justify-content:flex-end;margin-bottom:16px}.hint{margin-left:10px;color:#999}.el-pagination{margin-top:16px;justify-content:flex-end}.reward-thumb{width:56px;height:56px;border-radius:6px}.reward-preview{width:128px;height:128px;border:1px solid #dcdfe6;border-radius:8px;display:block}.remove-image{margin-left:12px}.upload-tip{color:#909399;font-size:12px;margin-top:6px}.reward-uploader{display:inline-block}</style>
